name: learn-github-actions
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: package setup
        uses: actions/checkout@v2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: show versions
        run: |
            python --version
            pip --version
      - name: lint package with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 actions --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 actions --count --max-complexity=10 --max-line-length=127 --statistics
      - name: run tests with pytest python version ${{ matrix.python-version }}
        run: |
          pytest tests
