name: code-cov
on:
  - push
  workflow_run:
    workflows: ["tests"]
    types:
      - completed
jobs:
  code-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Generate Coverage Report
      run: |
          git branch -vv
          coverage run -m --source=actions pytest tests -v
          coverage report --fail-under=100
