name: lint-and-test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: package setup
        uses: actions/checkout@v2
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: show versions
        run: |
            python --version
            pip --version

      - name: run tests with pytest (python version ${{ matrix.python-version }})
        run: |
          pytest tests
  lint:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: lint package with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 actions --count --select=E9,F63,F7,F82 --show-source --statistics

          # The GitHub editor is 127 chars wide
          flake8 actions --count --max-complexity=10 --max-line-length=127 --statistics

  code-coverage:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Generate Coverage Report
      run: |
          coverage run -m --source=actions pytest tests
          coverage report --fail-under=100
